ApeWorX/evm-trace

.pre-commit-config.yaml
README.md
evm_trace/base.py
evm_trace/display.py
evm_trace/enums.py
pyproject.toml
setup.py
tests/conftest.py
tests/test_call_tree.py
tests/test_trace_frame.py

Provide default tree via `__repr__` and `__str__` methods.
Inspired from the answer with 66 updoots: https://stackoverflow.com/questions/9727673/list-directory-tree-structure-in-python
print(tree)

feat: default displayable trace in repr and str for CallTreeNode

---

.github/workflows/test.yaml
evm_trace/vmtrace.py
setup.py

add support for `vmTrace` option in parity-style traces. this allows to get very similar data to geth debug traces, but it works an order of magnitude faster with the rpc responses being three orders of magnitude smaller.
unlike geth, which returns the storage and memory at each frame, this format returns incremental changes of which part of memory was overwritten or which items were pushed onto the stack, which is enough for us to recompute and return an iterator with up-to-date values at each frame at >200k frames/second.
i also added a map for opcodes consuming items from stack, since this info is not a part of the incremental updates.
i use py-evm primitives for an evm-compliant stack and memory implementations.
i also added the current contract address to the context of trace frame. …

feat: add vmTrace support

---

CONTRIBUTING.md
evm_trace/vmtrace.py

Changed the default value of `address` arg in `vmtrace:to_trace_frames` from `None` to `''`, since it's a `str` type.
Change `None` to `''`.
Run `pytest`.
(No need for new tests)
- [] New test cases have been added and are passing

fix: vmtrace:to_trace_frames address arg default value

---

evm_trace/base.py

Changing the display_nodes property to a method. This will help with creating a generic interface in ape core.

refactor: display_nodes prop -> get_display_nodes()

---

setup.py

Aligning setup with ape core, specifically HexBytes can't be 0.3.0 (latest version) due to an EF dependency trie that requires HexBytes < 0.3.0.

chore: update hexbytes pinning

---

setup.py

Currently the tests fail due to a missing module py-evm. 
```
vmtrace (unittest.loader._FailedTest) ... ERROR
======================================================================
ERROR: vmtrace (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: vmtrace
Traceback (most recent call last):
File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/loader.py", line 154, in loadTestsFromName
module = __import__(module_name)
File "/Users/alan/Code/evm-trace/evm_trace/vmtrace.py", line 5, in <module>
from eth.vm.memory import Memory  # type: ignore
ModuleNotFoundError: No module named 'eth' …
```

fix: Add missing py-evm dependency to `setup.py`

---

.pre-commit-config.yaml
evm_trace/gas.py
evm_trace/parity.py
evm_trace/vmtrace.py
setup.py
tests/conftest.py
tests/test_gas_report.py

I was having some issues and was not 100% convinced it wasn't coming from `evm-trace` so I improved the test to make me convinced.
Make test more complicated and transparent of what is happening

test: improve merge reports test

---

evm_trace/base.py
tests/test_trace_frame.py

`ValidationError` with missing memory.

fix: issue where could not handle missing memory

---

evm_trace/base.py
tests/test_trace_frame.py

For call traces (not transactions), the returndata in root is set a little different, but it was not letting me set it, so this PR changes the condition to only set the returndata from the frames if it not already set. This is also possibly an optimizations for other situations when the returndata is known ahead of time.
adjust `if` condition to also check that it is not already set (from `**root_node_kwargs`)

fix: issue where could not set returndata in root kwargs

---

.pre-commit-config.yaml
evm_trace/base.py
evm_trace/display.py
evm_trace/parity.py
evm_trace/vmtrace.py
setup.py

To more honorably honor the overrides and actually have them work, they should be set _after_ we build up the object from the call data.
Additionally, fixed many small things in the code base.
Adds in the `root_kwargs` at end of function instead of beginning.

fix: set root kwargs for parity trace at end of builder-logic

---

.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/feature.md
.github/ISSUE_TEMPLATE/work-item.md
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/commitlint.yaml
.github/workflows/prtitle.yaml
.github/workflows/publish.yaml
.github/workflows/test.yaml
.mdformat.toml
.pre-commit-config.yaml
README.md
evm_trace/gas.py
setup.py
tests/test_gas.py

Issue where had to have custom method for handling reports for when there was a single report.
Delete 2 identical, unneeded checks.
Can call `merge_reports` with single report.
I added a test!

fix: allow `merge_reports` to work with single report

---

.github/workflows/test.yaml
.pre-commit-config.yaml
evm_trace/enums.py
evm_trace/gas.py
evm_trace/geth.py
setup.py
tests/test_gas.py

* Support `merge_reports` handling 0 reports.. This can help clean up some Ape core code.
* Add `CREATE2` as a `CallType` - noticed it here: https://github.com/Ackee-Blockchain/woke/blob/main/woke/testing/call_trace.py#L39
* Pull out constant tuple `CALL_OPCODES`... This helps downstream usage of this library.
* Include `CALLCODE` as a handled `CallType`.. Seems like it is handled same as `STATICCALL` (https://github.com/Ackee-Blockchain/woke/blob/main/woke/testing/call_trace.py#L335)

fix: general improvements [APE-647]

---

evm_trace/__init__.py
evm_trace/geth.py
evm_trace/utils.py
tests/conftest.py
tests/test_geth.py

Adds a nice method for creating trace frames that handles the setting of CREATE2 addresses.
I think this is needed to find an annoying bug where source tracebacks are missing large chunks in the Ape framework.

feat: create trace frames function [APE-1336]

---

evm_trace/vmtrace.py

`sha3` opcode was renamed to `keccak256` in geth, and it got it renamed in erigon vmtrace output
https://github.com/ethereum/go-ethereum/pull/23976
https://github.com/ledgerwatch/erigon/pull/5890
add `keccak256` as alias for `sha3` opcode
vm tracing is broken in erigon post shanghai, but you can try [with this patch of mine](https://github.com/ledgerwatch/erigon/pull/7970).
as for reth, you can [track vmtrace compatibility here](https://github.com/paradigmxyz/reth/issues/4071), but it seems far from usable.

fix: add keccak256 as alias for sha3 opcode [APE-1262]

---

evm_trace/vmtrace.py

add a workaround for a bug present in latest stable erigon v2.48.1.
it is fixed in devel release, so we should remove the fix when erigon makes a new stable release.
https://github.com/ledgerwatch/erigon/pull/7970
fixes: #

fix: erigon push0 workaround [APE-1356]

---

setup.py

hoping for more proper python 3.10 and 3.11 support by upgrading eth..

chore: upgrade eth and other dependencies [APE-1615]

---

setup.py

We are able to do this to fix insalling with web3.py and ape rn
There is difference in the peer deps or the stuff we import in either version so it's fine.
increase range

fix: lower eth pin

---

.github/workflows/test.yaml
evm_trace/vmtrace.py
pyproject.toml
setup.py

Prep for 3.13 by removing msgspec dep and functionality when using it.

chore: prep for 3.13 by removing msgspec dep

---

evm_trace/display.py
setup.py

feat: implement cchecksum for ~2x faster checksumming

---

.pre-commit-config.yaml
evm_trace/geth.py
pyproject.toml
setup.py

Uses the new names of classes after eth_pydantic_types overhaul
fixes: #
in coordination with: https://github.com/ApeWorX/eth-pydantic-types/pull/11

feat: pydantic refactor

---

evm_trace/vmtrace.py
setup.py

reverted early PR now that msgspec is updated

feat: adds msgspec back in as it now supports python 3.13

---

setup.py

Notice there was a really annoying issue where we could not install web3 v7 because of a pinning issue between this lib and eth-tester (which is in `web3[tester]` extra)
~~- [ ] New test cases have been added and are passing~~
~~- [ ] Documentation has been updated~~

fix(deps): widen pin on py-evm as it causes issues w/ web3 v7
